"""
SQLAlchemy models for Artifact Management and Call Intelligence.

All files the system handles are tracked as Artifacts:
  - user-uploads: files manually uploaded by users
  - system-generated: files created by AI agents/tools

Storage path convention:
  artificate/{origin}/{company_id}/{YYYY-MM-DD}/{file_name}
  where origin is 'user-uploads' or 'system-generated'
"""
import uuid
from datetime import datetime
from sqlalchemy import (
    Column, String, Text, Integer, Boolean, DateTime, ForeignKey,
    Numeric, JSON, BigInteger
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from src.common.database import Base
from src.ai.models import HierarchicalEntity, ExecutionRun
from src.auth.models import Company


class Artifact(Base):
    """
    Tracks every file the platform saves — whether uploaded by a user or
    generated by an AI agent / tool.

    Storage roots:
      • user-uploads    → backend/artificate/user-uploads/{company_id}/…
      • system-generated → backend/artificate/system-generated/{company_id}/…
    """
    __tablename__ = "artifacts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    campaign_id = Column(UUID(as_uuid=True), ForeignKey("hierarchical_entities.id"), nullable=True)
    agent_id = Column(UUID(as_uuid=True), ForeignKey("hierarchical_entities.id"), nullable=True)
    run_id = Column(UUID(as_uuid=True), ForeignKey("execution_runs.id"), nullable=True)

    # Origin: who produced this file
    origin = Column(String(30), nullable=False)        # user-uploads | system-generated

    # What kind of content this is
    file_category = Column(String(50), nullable=False) # recordings | images | videos | documents | text
    file_name = Column(String(500), nullable=False)
    file_path = Column(Text(), nullable=False)          # Absolute path on disk
    file_size = Column(BigInteger, nullable=True)       # bytes
    duration_seconds = Column(Integer, nullable=True)  # For audio/video
    mime_type = Column(String(100), nullable=True)

    # Provenance — why was this created and by what
    purpose = Column(Text, nullable=True)              # Human-readable description
    generated_by = Column(String(200), nullable=True)  # Tool / agent / process name (e.g. 'image_generation', 'pdf_generator')

    artifact_metadata = Column(JSON, nullable=True)    # Extra info (dimensions, call SID, model used, etc.)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    company = relationship("Company")
    campaign = relationship("HierarchicalEntity", foreign_keys=[campaign_id])
    agent = relationship("HierarchicalEntity", foreign_keys=[agent_id])
    run = relationship("ExecutionRun")

    # Back-reference from call_content
    call_contents = relationship("CallContent", back_populates="audio_artifact")


class CallLog(Base):
    """
    Telephony call metadata for call intelligence and reporting.
    """
    __tablename__ = "call_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False)
    voice_session_id = Column(UUID(as_uuid=True), nullable=True)   # Ref to voice_sessions (no FK: different module)
    agent_id = Column(UUID(as_uuid=True), ForeignKey("hierarchical_entities.id"), nullable=True)

    direction = Column(String(20), nullable=True)       # inbound | outbound
    status = Column(String(30), nullable=True)          # completed | failed | no-answer
    duration_seconds = Column(Integer, nullable=True)
    from_number = Column(String(30), nullable=True)
    to_number = Column(String(30), nullable=True)
    provider = Column(String(30), nullable=True)        # twilio | tata_tele
    call_cost_usd = Column(Numeric(10, 6), nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    company = relationship("Company")
    agent = relationship("HierarchicalEntity")
    content = relationship("CallContent", back_populates="call_log", uselist=False)


class CallContent(Base):
    """
    Transcript and summary for a call, with a reference to the audio recording artifact.
    """
    __tablename__ = "call_content"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    call_log_id = Column(UUID(as_uuid=True), ForeignKey("call_logs.id"), nullable=False)
    audio_artifact_id = Column(UUID(as_uuid=True), ForeignKey("artifacts.id"), nullable=True)

    transcript_text = Column(Text, nullable=True)
    summary_text = Column(Text, nullable=True)
    sentiment = Column(String(20), nullable=True)    # positive | neutral | negative
    content_metadata = Column(JSON, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    call_log = relationship("CallLog", back_populates="content")
    audio_artifact = relationship("Artifact", back_populates="call_contents")
