"""Refactor Hierarchical AI Platform Phase 3

Revision ID: 9bc12d4c6cc6
Revises: 09e4d21677b1
Create Date: 2025-12-27 09:08:01.444977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc12d4c6cc6'
down_revision: Union[str, Sequence[str], None] = '09e4d21677b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_trigger', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('responded_by', sa.UUID(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('timeout_ms', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_interaction_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('input_parameters', sa.JSON(), nullable=True),
    sa.Column('output_result', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('execution_runs', sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('execution_runs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('execution_runs', sa.Column('execution_time_ms', sa.Integer(), nullable=True))
    op.add_column('execution_runs', sa.Column('trace_id', sa.UUID(), nullable=True))
    op.add_column('execution_runs', sa.Column('span_id', sa.String(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('version', sa.String(), nullable=False, server_default='1.0.0'))
    op.add_column('hierarchical_entities', sa.Column('status', sa.String(), nullable=False, server_default='ACTIVE'))
    op.add_column('hierarchical_entities', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('identity', sa.JSON(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('hierarchy', sa.JSON(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('logic_gate', sa.JSON(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('planning', sa.JSON(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('capabilities', sa.JSON(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('governance', sa.JSON(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('io_contract', sa.JSON(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('observability', sa.JSON(), nullable=True))
    op.add_column('hierarchical_entities', sa.Column('metadata_extensions', sa.JSON(), nullable=True))
    op.add_column('llm_interaction_logs', sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('llm_interaction_logs', sa.Column('reasoning_mode', sa.String(), nullable=True))
    op.add_column('llm_interaction_logs', sa.Column('log_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_interaction_logs', 'log_metadata')
    op.drop_column('llm_interaction_logs', 'reasoning_mode')
    op.drop_column('llm_interaction_logs', 'cost_usd')
    op.drop_column('hierarchical_entities', 'metadata_extensions')
    op.drop_column('hierarchical_entities', 'observability')
    op.drop_column('hierarchical_entities', 'io_contract')
    op.drop_column('hierarchical_entities', 'governance')
    op.drop_column('hierarchical_entities', 'capabilities')
    op.drop_column('hierarchical_entities', 'planning')
    op.drop_column('hierarchical_entities', 'logic_gate')
    op.drop_column('hierarchical_entities', 'hierarchy')
    op.drop_column('hierarchical_entities', 'identity')
    op.drop_column('hierarchical_entities', 'tags')
    op.drop_column('hierarchical_entities', 'display_name')
    op.drop_column('hierarchical_entities', 'status')
    op.drop_column('hierarchical_entities', 'version')
    op.drop_column('execution_runs', 'span_id')
    op.drop_column('execution_runs', 'trace_id')
    op.drop_column('execution_runs', 'execution_time_ms')
    op.drop_column('execution_runs', 'total_tokens')
    op.drop_column('execution_runs', 'total_cost_usd')
    op.drop_table('tool_interaction_logs')
    op.drop_table('human_approvals')
    # ### end Alembic commands ###
