"""Remove legacy Partner and Tenant tables

Revision ID: c3e80da7ca0a
Revises: c830b1839465
Create Date: 2025-12-18 11:40:12.751696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3e80da7ca0a'
down_revision: Union[str, Sequence[str], None] = 'c830b1839465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop external constraints first
    op.drop_constraint(op.f('ledger_entries_partner_id_fkey'), 'ledger_entries', type_='foreignkey')
    op.drop_constraint(op.f('partner_rates_partner_id_fkey'), 'partner_rates', type_='foreignkey')
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    
    # Drop tables (tenants first because it depends on partners)
    op.drop_table('tenants')
    op.drop_table('partners')
    
    # Create new foreign keys to companies
    op.create_foreign_key(None, 'ledger_entries', 'companies', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'partner_rates', 'companies', ['partner_id'], ['id'])
    
    # Drop the legacy column
    op.drop_column('users', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'partner_rates', type_='foreignkey')
    op.create_foreign_key(op.f('partner_rates_partner_id_fkey'), 'partner_rates', 'partners', ['partner_id'], ['id'])
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.create_foreign_key(op.f('ledger_entries_partner_id_fkey'), 'ledger_entries', 'partners', ['partner_id'], ['id'])
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('partner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('tenants_company_id_fkey')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('tenants_partner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey'))
    )
    op.create_table('partners',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admin_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('partners_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('partners_pkey'))
    )
    # ### end Alembic commands ###
