"""Refactor to Company and hierarchical RBAC

Revision ID: c830b1839465
Revises: 6fdc110c5698
Create Date: 2025-12-18 11:11:54.761547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c830b1839465'
down_revision: Union[str, Sequence[str], None] = '6fdc110c5698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('agents_tenant_id_fkey'), 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'companies', ['company_id'], ['id'])
    op.drop_column('agents', 'tenant_id')
    op.add_column('documents', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('documents_tenant_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'companies', ['company_id'], ['id'])
    op.drop_column('documents', 'tenant_id')
    op.add_column('executions', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('executions_tenant_id_fkey'), 'executions', type_='foreignkey')
    op.create_foreign_key(None, 'executions', 'companies', ['company_id'], ['id'])
    op.drop_column('executions', 'tenant_id')
    op.add_column('invoices', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('invoices_tenant_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'companies', ['company_id'], ['id'])
    op.drop_column('invoices', 'tenant_id')
    op.add_column('ledger_entries', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('ledger_entries_tenant_id_fkey'), 'ledger_entries', type_='foreignkey')
    op.create_foreign_key(None, 'ledger_entries', 'companies', ['company_id'], ['id'])
    op.drop_column('ledger_entries', 'tenant_id')
    op.add_column('partners', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'partners', 'companies', ['company_id'], ['id'])
    op.add_column('payment_methods', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('payment_methods_tenant_id_fkey'), 'payment_methods', type_='foreignkey')
    op.create_foreign_key(None, 'payment_methods', 'companies', ['company_id'], ['id'])
    op.drop_column('payment_methods', 'tenant_id')
    op.add_column('subscriptions', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('subscriptions_tenant_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'companies', ['company_id'], ['id'])
    op.drop_column('subscriptions', 'tenant_id')
    op.add_column('tenants', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tenants', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.add_column('workflows', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('workflows_tenant_id_fkey'), 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'companies', ['company_id'], ['id'])
    op.drop_column('workflows', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key(op.f('workflows_tenant_id_fkey'), 'workflows', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('workflows', 'company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'company_id')
    op.add_column('subscriptions', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_tenant_id_fkey'), 'subscriptions', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('subscriptions', 'company_id')
    op.add_column('payment_methods', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment_methods', type_='foreignkey')
    op.create_foreign_key(op.f('payment_methods_tenant_id_fkey'), 'payment_methods', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('payment_methods', 'company_id')
    op.drop_constraint(None, 'partners', type_='foreignkey')
    op.drop_column('partners', 'company_id')
    op.add_column('ledger_entries', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.create_foreign_key(op.f('ledger_entries_tenant_id_fkey'), 'ledger_entries', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('ledger_entries', 'company_id')
    op.add_column('invoices', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_tenant_id_fkey'), 'invoices', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('invoices', 'company_id')
    op.add_column('executions', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.create_foreign_key(op.f('executions_tenant_id_fkey'), 'executions', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('executions', 'company_id')
    op.add_column('documents', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_tenant_id_fkey'), 'documents', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('documents', 'company_id')
    op.add_column('agents', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key(op.f('agents_tenant_id_fkey'), 'agents', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('agents', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
